# Generated by Django 2.2.1 on 2019-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190507_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Anonymous', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('POL', 'Politics'), ('SCI', 'Science'), ('FOO', 'Food'), ('TEC', 'Technology'), ('FAS', 'Fashion'), ('ADV', 'Advice'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
