# Generated by Django 2.2.1 on 2019-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190510_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('POL', 'Politics'), ('SCI', 'Science'), ('FOO', 'Food'), ('TEC', 'Technology'), ('FAS', 'Fashion'), ('ADV', 'Advice'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
    ]
